services:
  - type: web
    name: fake-news-detector-api
    runtime: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TAVILY_API_KEY
        scope: all
      - key: GROQ_API_KEY
        scope: all
